name: build.yml
on:
  push:
    branches:
      - "master"

env:
  # default: ghcr.io
  REGISTRY: ghcr.io
  # default: ./Dockerfile
  DOCKERFILE: ./DiscordBot/Dockerfile
  # <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ${{env.REGISTRY}}
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Bump version and push tag
        id: tag_version
        uses: anothrNick/github-tag-action@v1 # Don't use @master or @v1 unless you're happy to test the latest version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image for API Server
        env:
          VERSION: ${{ steps.tag_version.outputs.tag }}
        run: |
          echo "Building image version ${{ env.IMAGE_NAME }}:$VERSION"
          # build into 2 images
          docker build --label version=$VERSION -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:$VERSION -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest -f ${{ env.DOCKERFILE }} .
          # push images
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:$VERSION
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest

      - name: Update staging container
        run: curl -X POST ${{ secrets.STAGING }}